[build.environment]
  NPM_VERSION = "6.13.4"

[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build:preview"

[dev]
  command = "npm run start"
  targetPort = 8888

[[redirects]]
  from = "/netlify/anything"
  to = "https://www.google.com/search?q=anything"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
